### ISSUE TITLE
stralink_grpc response error

### ISSUE THREAD

**Issue by archerne** [archerne/hastarlink#5]
From HA forum:
```Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py", line 71, in async_step_confirm
    has_devices = await cast(
  File "/config/custom_components/starlink/config_flow.py", line 14, in _async_has_devices
    devices = await api_client.get()
  File "/config/custom_components/starlink/__init__.py", line 174, in get
    response = _dish_grpc_text.main(obj)
  File "/config/custom_components/starlink/dish_grpc_text.py", line 288, in main
    lines.append(self.loop_body(opts, gstate, print_file))
  File "/config/custom_components/starlink/dish_grpc_text.py", line 239, in loop_body
    rc, status_ts, hist_ts = self._dish_common.get_data(opts,
  File "/config/custom_components/starlink/dish_common.py", line 233, in get_data
    rc, status_ts = self.get_status_data(
  File "/config/custom_components/starlink/dish_common.py", line 274, in get_status_data
    groups = starlink_grpc.status_data(context=gstate.context)
  File "/usr/local/lib/python3.10/site-packages/starlink_grpc.py", line 765, in status_data
    "wedges_fraction_obstructed[]": status.obstruction_stats.wedge_abs_fraction_obstructed,
AttributeError: 'DishObstructionStats' object has no attribute 'wedge_abs_fraction_obstructed'```

**Comment by archerne** [comment]
It appears as though the response from the dish doesn't have the attribute `wedge_abs_fraction_obstructed` in it. I am now getting the same error on my starlink this morning since it updated. I have submitted a ticket to the python library

**Comment by archerne** [comment]
Will be fixed with https://github.com/sparky8512/starlink-grpc-tools/issues/65
