### ISSUE TITLE
Bug with Home Assistant 2022.12.4

### ISSUE THREAD

**Issue by tlamoureux24** [archerne/hastarlink#9]
Hello,

I'm using your integrations without problem before but since the last update 2022.12.4 it doesn't work anymore.
I try totally remove and reinstall and still the same.
I'm running Home Assistant Supervised on a Debian 11

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 281, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py", line 71, in async_step_confirm
    has_devices = await cast(
  File "/config/custom_components/starlink/config_flow.py", line 14, in _async_has_devices
    devices = await api_client.get()
  File "/config/custom_components/starlink/__init__.py", line 183, in get
    if responseObj["latitude"] == '':
KeyError: 'latitude'

Let me know if you need more details.

Thank you

PS : sorry for my bad english, i'm french :(

**Comment by archerne** [comment]
What version firmware is your starlink currently on? I am on 2022.12.4 HA and mine is still working. My starlink is currently: f562e306-0cd5-44c2-9058-9ab6800c4b50.uterm.release

This appears to just be that latitude isn't in the response object, but that would be a weird key for them to remove.

**Comment by tlamoureux24** [comment]
I have version f562e306-0cd5-44c2-9058-9ab6800c4b50.uterm.release

**Comment by tlamoureux24** [comment]
Maybe it could help, I use starlink router in bypass mode and i have
activate the starlink location in advanced debug mode since the beginning
and no problem before ....

**Comment by tlamoureux24** [comment]
Solved after reinstalling the whole system (debian+HA)
